org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

## Environment
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.219
neo_version_range=[21.1.200,)
loader_version_range=[4,)

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

## Mod
mod_id=eyesoficeandfire
mod_name=Eyes of Ice and Fire Community Edition
mod_license=LGPL-3.0
mod_version=1.3.0-1.21.1
mod_group_id=io.github.lucianowayand.eyesoficeandfire
mod_authors=LucianoWayand, Groupix05, Infernos/Imbavirus
mod_description=Unofficial 1.21.1 NeoForge port of Eyes of Ice and Fire CE. Locate nearby Ice and Fire CE dragons with lore-friendly eyes of ender crafted from dragon blood.
